server:
  port: 8889
  servlet:
    session:
      timeout: 10s
      cookie:
        http-only: true # 保证cookie更安全
        secure: false
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#  security:
#    user:
#      name: admin
#      password: admmin
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/security_study?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: gao123456
    driver-class-name: com.mysql.jdbc.Driver
  freemarker:
    cache: false # 缓存配置 开发阶段应该配置为false 因为经常会改
    suffix: .html # 模版后缀名 默认为ftl
    charset: UTF-8 # 文件编码
    template-loader-path: classpath:/templates/
  security:
    loginType: JSON

#mybatis:
#  configuration:
#    mapUnderscoreToCamelCase: true

jwt:
  secret: ffjaksdfjaklf
  expiration: 3600000
  header: JWTHeaderName